### ISSUE TITLE
세션 상세 페이지로 전환에 관련된 논의

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#13]
## Kind (Required)

- Other

## Overview (Required)
현재 Single Activity 구조에 BottomNavigationView와 Jetpack Navigation을 연결하여 화면 전환을 하고 있는데, SessionDetailFragment를 띄울 땐 새로운 창으로 보여졌으면 합니다.

1. 이 때, Activity 위에 MainFragment를 두고 그 내에서 BottomNavigationView 화면전환 페이지와 SessionDetailFragment를 따로 관리할지 
2. 아니면 그냥 Single Activity 구조를 버리고 세션 상세는 새로운 Activity를 띄울지 고민이 됩니다. 🤔
## Links

- https://github.com/droidknights/DroidKnights2020_App/blob/master/androidapp/app/src/main/java/com/droidknights/app2020/ui/schedule/detail/SessionDetailFragment.kt

**Comment by leeyc09** [comment]
하단 네비게이션을 덮는 레이아웃을 가지고 가려면 singleActivity 구조로는 안되지 않을까요?
SessionDetailActivity - SessionDetailFragment 구조로 만들고 별도의 네비게이션 설정 xml을 만든 후
처리해야 할 것 같아요.

**Comment by gylee2011** [comment]
특정 destination에 대해서 bottom nav를 숨기는 식으로 하는 건 어떨까요?
[여기](https://stackoverflow.com/questions/51955357/hide-android-bottom-navigation-view-for-child-screens-fragments) 참고해서 시험삼아 NavController에 [NavController.OnDestinationChangedListener](https://developer.android.com/reference/androidx/navigation/NavController.OnDestinationChangedListener)를 추가해서
```
binding.bottomNav.isVisible = (destination.id != R.id.sessionDetailFragment)
```
이렇게 하니까 되긴 되네요.

**Comment by Pluu** [comment]
`Single Activity`로 가신다면 편법보다는 1번의 방법을 권해드려요.

**Comment by laco-dev** [comment]
@gylee2011 님 방식으로 해결한 적이 있어요.
MainActivity에서 현재 프래그먼트 아이디를 비교해서 Bottom Nav에 애니메이션으로 숨기거나 나타내거나 애니메이션을 넣어봤는데 이 방법도 괜찮더라구요.

**Comment by Jiyoung9310** [comment]
앱 기획 변경의 이유로 이슈 잠시 닫겠습니다. (필요 시, 다시 재오픈합니다.)
