### ISSUE TITLE
홈 화면 구성하기

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#133]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 디자인에 맞게 홈 화면을 재구성 합니다.
- **반드시** 제플린에 있는 코멘트를 확인해주세요!
- <img src ="https://user-images.githubusercontent.com/7722921/91664582-2d0a6b00-eb2b-11ea-96ea-1666a2a8a6a2.png" width=300>
- toolbar title 에 "소개" 로 표시됩니다.
- toolbar 와 bottom navigation 사이 화면은 전체적으로 스크롤이 가능해야 합니다.
- 연도별 개최되었던 드로이드나이츠 행사 리스트가 표시됩니다.
- 각 리스트 아이템 클릭 시, 드로이드나이츠 홈페이지로 이동합니다. (SponsorFragment클래스에 openWebUrl 함수 참고)

 ## Links	

- 제플린 : https://zpl.io/awKlmjj (로그인계정 : z023@kakao.com / asdf1234!!)

**Comment by Pluu** [comment]
@Jiyoung9310 후원사 부분은 스크롤하지않으면 전부 노출하지않는지 확인이 필요합니다.

모든 후원사가 기본적으로 노출은 해야하는것이 아닌가요?

**Comment by Jiyoung9310** [comment]
> @Jiyoung9310 후원사 부분은 스크롤하지않으면 전부 노출하지않는지 확인이 필요합니다.
> 
> 모든 후원사가 기본적으로 노출은 해야하는것이 아닌가요?

@Pluu 자동으로 스크롤 되어서 움직이는 배너처럼 보이게끔 하는 것이 목표입니다. 해당 구현은 따로 이슈 생성하겠습니다

**Comment by Pluu** [comment]
🙋‍♂️
