### ISSUE TITLE
세션 상세 화면에 Speaker 정보 표시하기

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#136]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 세션 상세 화면(SessionDetailFragment)에 Speaker 정보를 추가적으로 표시합니다.
- Session 클래스에 speaker 데이터를 활용합니다.
- 세션에 대한 전반적인 데이터는 sessions.json 파일을 참고하세요.
- 연사자 프로필 사진, 이름, 자기소개를 상세 화면에 표시합니다.
- 프로필 사진은 이미지 라이브러리를 활용합니다. (작업자가 편한 라이브러리 사용해주세요.)

 ## Links	

- 레이아웃 참고 : https://docs.google.com/presentation/d/1ka9trEJrx-cDt98uG1j6DJRcNFtRZHggk_8OAqZdog8/edit?usp=sharing
- 디자인은 아직 없습니다. 추후 나올 예정입니다.

**Comment by Pluu** [comment]
🙋‍♂️

**Comment by Pluu** [comment]
@Jiyoung9310 DB에 소속 정보가 누락된듯 하네요

**Comment by Jiyoung9310** [comment]
> @Jiyoung9310 DB에 소속 정보가 누락된듯 하네요

앗, 이부분 지금 추가작업 후에 다시 안내 드리겠습니다! (약 1시간 예상)

**Comment by Jiyoung9310** [comment]
@Pluu 서버에 `belong` 데이터 추가되었습니다. (#137 참고)
