### ISSUE TITLE
세션 상세 화면 디자인 작업

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#139]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 세션 상세 화면에 디자인을 입히는 작업을 합니다.
- **반드시** 제플린에 있는 코멘트를 확인해주세요.
- **제플린에 누락된 내용** : 세션 소개 아래에 연사자 소개 내용이 추가적으로 표시되어야 합니다.
- <img src = "https://user-images.githubusercontent.com/7722921/91780087-83fa6800-ec31-11ea-9ca3-2225047758d5.png" width=300 />
- 세션 소개와 연사자 소개 구분선 두께 1dp, color #f1f1f1 
- 연사자 소개 타이틀과 내용 textColor, textSize 는 내용 소개와 동일하게 맞춥니다.
- 나머지 상세 요구사항들은 제플린 코멘트로 확인할 수 있습니다.

(관련된 작업 #136 #138 )

 ## Links	

- 제플린 : https://zpl.io/brwRRo1 (로그인 계정 z023@kakao.com / asdf1234!!)

**Comment by improve777** [comment]
🙋‍♀️🙋🙋‍♂️

**Comment by Jiyoung9310** [comment]
@improve777 🙇‍♀️
