### ISSUE TITLE
앱 아이콘 설정

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#14]
## Kind (Required)
- Improvement

## Overview (Required)
- 앱의 얼굴이 될 아이콘을 설정해주세요.

## Links
- ~https://drive.google.com/file/d/1MSF_dcqecPsXubNXOjcHpPzAMjozizc_/view~

**Comment by fornewid** [comment]
svg 파일은 없나요? 👀 
있으면 제가 해봐도 될까요?

**Comment by Jiyoung9310** [comment]
@fornewid svg 리소스 먼저 확보하고나서 할당드리도록 하겠습니다!🙌

**Comment by Jiyoung9310** [comment]
@fornewid 시간이 너무 많이 지나버려서 죄송합니다..

**Comment by fornewid** [comment]
음.. [링크에 있는 이미지](https://lh3.googleusercontent.com/i7ZUx0wvKgf6t24wW0hqgH4MvRv8oPYDP5vjj3O5arwUtPYRGH0KO8yHLCpS4LSpDw__G4DT0h1hqmDz1D4K=w2880-h1480-rw)가 background layer도 포함된 것 같아요.
foreground layer만 분리된 이미지 파일은 없을까요?

**Comment by Jiyoung9310** [comment]
@fornewid 배경이 투명인 이미지 https://drive.google.com/file/d/1M8QE1t9QAupX3t2MyhzJUAOSkbEyNt-r/view?usp=sharing 여기 업로드 하였습니다~
