### ISSUE TITLE
홈 화면 툴바 추가하기

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#142]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 홈 화면에 툴바를 추가합니다.
- height : 60dp
<img width="592" alt="스크린샷 2020-09-02 오전 9 12 38" src="https://user-images.githubusercontent.com/7722921/91917975-7a8a0200-ecfc-11ea-8317-aeca3c476ab9.png">

 ## Links	

- 제플린 : https://zpl.io/VKM3gKE (로그인 계정 z023@kakao.com / asdf1234!!)

**Comment by yands11** [comment]
🙋‍♂️
