### ISSUE TITLE
세션 페이지 refresh 추가

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#17]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 세션 스케줄표 리스트에 pull to refresh 동작을 구현합니다

 ## Links	

-

**Comment by yands11** [comment]
한번 도전해볼게요!

**Comment by Pluu** [comment]
@yands11 Thank you 🙇🏻‍♂️

**Comment by yands11** [comment]
구현 중에 궁금한 사항이 있어서 질문드립니다.
sessionList를 불러오는 도중에 보여줄 로딩인디케이터로 Progressbar가 존재하고 있는 것 같습니다. 
(아직 구현은 안되어서 확실하지 않지만요.)
그래서 `SwipeRefreshLayout`를 추가하게되면서 단순히 트리거된 후에는 바로 `isRefreshing=false`을 해주면서 Progressbar만 보여질지, Progressbar와 중복으로 화면에 노출되어야하는지 궁금합니다.

**Comment by Jiyoung9310** [comment]
@yands11 둘다 중복되게 나올 필요는 없을 것 같은데 🤔, 기존에 있는 Progressbar 는 굳이 계속 사용하지 않으셔도 괜찮습니다!
