### ISSUE TITLE
세션 리스트에 디자인 적용

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#18]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 세션 리스트에 디자인을 적용합니다

 ## Links	

+추가
- https://zpl.io/a7BpNDq
- z023@kakao.com / asdf1234!!

**Comment by Jiyoung9310** [comment]
디자인 확인용 제플린 링크 및 계정 정보 추가

**Comment by leeyc09** [comment]
제가하겠습니다.

**Comment by leeyc09** [comment]
#42 가 머지가 안되어 있어서 별도로  #47  이슈를  발행하여 #48 아이템디자인만 적용시켰습니다.

**Comment by Jiyoung9310** [comment]
앱 기획 변경의 이유로 이슈 잠시 닫겠습니다. (필요 시, 다시 재오픈합니다.)
