### ISSUE TITLE
스폰서 회사 로고 이미지 표시

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#20]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 스폰서 페이지에 회사 로고를 표시합니다. height = 50dp
- 이미지 리소스 drawable-xxxhdpi 에 위치
<img width="254" alt="스크린샷 2020-02-07 오후 3 06 41" src="https://user-images.githubusercontent.com/7722921/74005201-78a4ce00-49bb-11ea-8e58-15e0892cc5ca.png">

+추가
- 순서는 다이아 > 플레티넘 > 골드 순으로 배치합니다.
       다이아 : 토스 
       플레티넘 : 헤이딜러, 라인, 리멤버
       골드 : 강남언니, 네이버, 마이리얼트립, 카카오페이 ,vcnc

 ## Links	

-

**Comment by Pluu** [comment]
@Jiyoung9310 스폰서 이미지 배치에 대한 가이드 갱신이 필요합니다

**Comment by Jiyoung9310** [comment]
@Pluu 정보 추가하였습니다!

**Comment by mkw8263** [comment]
Assignees 받고싶습니다!

**Comment by Jiyoung9310** [comment]
@mkw8263 담당자 할당 드렸습니다 참여 감사합니다!

**Comment by mkw8263** [comment]
![image](https://user-images.githubusercontent.com/20398201/74166489-fe4da580-4c69-11ea-8263-e738ca2a99da.png)

@Jiyoung9310 
토스, 리멤버,마이리얼트립, vcnc 이미지(흰색 로고)에 대해서 별도 처리가 있을까요?

**Comment by Jiyoung9310** [comment]
@mkw8263 엇 🤔 일단 배경 컬러를 #303033 으로 두고 완료해주시고, 나중에 디자인 나오면 추가로 작업 요청 드려도 될까요?

**Comment by mkw8263** [comment]
@Jiyoung9310 
옙 일단 배경컬러는 말씀 해주신 컬러로 완료했습니다!
추후 디자인 시안 나올때 까지 해당 이슈는 홀딩 하고있을까요?

**Comment by Jiyoung9310** [comment]
@mkw8263 일단 먼저 올려주시면 이슈 close 하고, 추가 요청 건 있을시 리오픈 하겠습니다! 감사합니다
