### ISSUE TITLE
스폰서 로고 클릭 이벤트 추가

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#21]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 스폰서 페이지에서 로고를 클릭하면 해당 url로 이동하면서 웹뷰를 띄웁니다.
- 외부 브라우저를 통해서가 아닌, 앱 내부에 웹뷰로 링크를 이동시키도록 합니다.

 ## Links	

-

**Comment by kts6056** [comment]
제가 한번 도전해보겠습니다!

**Comment by Pluu** [comment]
@kts6056 Thank you

**Comment by Pluu** [comment]
@kts6056 내용 갱신을 부탁드립니다.

**Comment by kts6056** [comment]
> @kts6056 내용 갱신을 부탁드립니다. 

죄송합니다 제가 시간을 너무 지체하였네요...
주말에 작업하여 PR을 올리도록 하겠습니다.
