### ISSUE TITLE
Scabbard 플러그인 추가

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#22]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Dagger graph를 시각화 시켜주는 Scabbard 플러그인을 추가합니다.

 ## Links	

- 참고자료 : https://arunkumar9t2.github.io/scabbard/
https://pluu.github.io/blog/android/2019/12/29/dagger-scabbard/

**Comment by mkw8263** [comment]
해당 이슈 Assignees 받을수있을까요!?

**Comment by Jiyoung9310** [comment]
@mkw8263 먼저 할당드린 #20 이슈부터 작업해주시면 감사하겠습니다!

**Comment by mkw8263** [comment]
@Jiyoung9310 
요거 작업 받을수있을까요!?

**Comment by Pluu** [comment]
@mkw8263 Thank you
