### ISSUE TITLE
세션 리스트 데이터 못가져올 경우 로컬 데이터로 표시

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#23]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 네트워크 상태가 안좋을 때나 세션 리스트 데이터를 못가져올 경우, sessions.json 데이터로 세션 리스트를 표시합니다.
![image](https://user-images.githubusercontent.com/7722921/74101598-c3227800-4b7e-11ea-94fb-535ed68da050.png)

 ## Links	

-

**Comment by fornewid** [comment]
🙋🏻‍♂️

**Comment by Pluu** [comment]
@fornewid Thank you

**Comment by fornewid** [comment]
Json Parser는 어떤걸 선호하시나요?
1) [kotlinx serialization](https://github.com/Kotlin/kotlinx.serialization)
2) Gson
3) Jackson
4) Moshi

**Comment by fornewid** [comment]
Kotlinx serialization으로 갑니당~ 🚀

**Comment by Pluu** [comment]
@fornewid 현재 나온 안정버전인 Moshi 혹은 Gson이 되어야할 듯 하네요.
kotlinx serializatio 의 안전성을 좀 더 고려해봐야하지 않을까 싶습니다
