### ISSUE TITLE
오픈소스 라이브러리 소개 페이지 추가

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#26]
## Kind (Required)

- Improvement

 ## Overview (Required)

- mypage 페이지에 오픈소스 라이브러리 리스트를 보여줄 버튼을 추가합니다.
- 새 창이 뜨면서 앱 구현에 사용된 오픈소스 라이브러리를 보여줍니다.

 ## Links	

-

**Comment by kts6056** [comment]
한번 제가 도전해 보겠습니다~!

**Comment by Pluu** [comment]
@kts6056 Thank you

**Comment by Pluu** [comment]
@kts6056 내용 갱신을 부탁드립니다.

**Comment by kts6056** [comment]
> @kts6056 내용 갱신을 부탁드립니다. 

주말동안 오픈소스 리스트 표시 방법과 라이선스 내용을 어떻게 유저에게 보여줄지 구상을 하고 다시 코멘트 남기도록 하겠습니다 늦어서 죄송합니다.

**Comment by pish11010** [comment]
위의 분이 진행이 안되셨다면 google play services plugin의 oss-license 로 빠르게 처리해보겠습니다.

**Comment by kts6056** [comment]
@pish11010 
깜박하고 있었네요 ㅜㅜ 저때 당시 아직 메인 화면이 없어 진행을 못 했었습니다. 
감사합니다.
