### ISSUE TITLE
스폰서 이미지 갱신

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2020_App#32]
## Kind (Required)
- Other

 ## Overview (Required)
- 원본 스폰서 이미지의 규격이 없습니다.
   - 예) 이미지마다 여백 포함 여부가 상이합니다.
- 통일된 이미지 형태로 정리된 이미지 처리가 필요합니다.

**Comment by Jiyoung9310** [comment]
앱 기획 변경의 이유로 이슈 잠시 닫겠습니다. (필요 시, 다시 재오픈합니다.)
