### ISSUE TITLE
스폰서 XML Preview 갱신

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2020_App#34]
## Kind (Required)
- Improvement

## Overview (Required)
- XML에서 개발시 Preview 화면에 더욱 알기 쉽게 기본 정보를 노출할 수 있습니다.
- 아래의 기능 추가 기다리고 있습니다
   1. [tools:listitem](https://developer.android.com/studio/write/tool-attributes?hl=ko#toolslistitem_toolslistheader_toolslistfooter)
   2. ["@tools:sample/*" resources](https://developer.android.com/studio/write/tool-attributes?hl=en#toolssample_resources)

### Preview (Add, 2020/02/13)
- Preview로 나오는 형태는 실제 스폰서의 이름과 이미지를 노출하길 원합니다.

## Links	
- https://developer.android.com/studio/write/tool-attributes

## Screenshot (변경 전)
| 변경전 | 변경후 |
| :-: | :-: |
| <img width="450" src="https://user-images.githubusercontent.com/1534926/74351907-1bfe4480-4dfb-11ea-8375-be1a5c9ff978.png"/> | <img width="450" src="https://user-images.githubusercontent.com/1534926/74445695-259ab180-4eba-11ea-8044-20a70f74aa52.png" />

**Comment by lhoyong** [comment]
🙋‍♂️

**Comment by Pluu** [comment]
@lhoyong Thank you 🙇🏻‍♂️
