### ISSUE TITLE
스폰서 XML Preview 갱신 2

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2020_App#44]
## Kind (Required)
- Improvement

## Overview (Required)
- XML Preview의 기능 중 하나로 Sample은 더 자연스러운 Preview 효과를 얻을 수 있습니다.
- sample 폴더에 스폰서 이미지가 포함된 상태입니다.
- sample 폴더에 스폰서 이미지를 추가하지 않고 현재 Preview와 동일하게 노출하는 방법을 원합니다.

## Links	
- https://developer.android.com/studio/write/tool-attributes?hl=en#toolssample_resources

## Screenshot
<img width="383" alt="스크린샷 2020-02-14 오후 11 11 31" src="https://user-images.githubusercontent.com/1534926/74538408-850ec500-4f7f-11ea-8327-28253d6f6294.png">

**Comment by lagoJin** [comment]
🙋‍♂️

**Comment by Pluu** [comment]
@lagoJin Thank you

**Comment by lagoJin** [comment]
@Pluu 잘못 눌러서 assingment가 풀렸습니다. 다시 추가해주실 수 있나요?

**Comment by Pluu** [comment]
@lagoJin Done!
