### ISSUE TITLE
제플린 디자인 가이드와 하단네비게이션 항목 다른 이슈

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#46]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 기존 코드에는 하단 메뉴가 정보 / 세션 / 스폰서 / 프로필
- 제플린에는 이벤트 정보 / 세션 / 프로필 로 서로 상이한 문제가 있습니다.

- '정보'와 '스폰서' 메뉴를 합쳐서 '이벤트 정보' 페이지 한 화면에 구현합니다.

 ## Links	

-

<img src="https://user-images.githubusercontent.com/7722921/74600155-aaf7af00-50d0-11ea-94ba-7553f76c2bdd.png" width="40%">

**Comment by leeyc09** [comment]
@Jiyoung9310 제플린에서 하단 아이콘을 가지고 올 수 없습니다.

**Comment by Jiyoung9310** [comment]
@leeyc09 메뉴 합치기와 메뉴 디자인 적용 이슈를 분리하겠습니다
