### ISSUE TITLE
Migration, firebase-core

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2020_App#52]
## Kind (Required)
- Improvement

 ## Overview (Required)
- Firebase의 `com.google.firebase:firebase-core` 작업은 더이상 추가하지 않습니다. 
- 새로운 종속성 개선 처리를 할 필요가 있습니다.

 ## Links	
- https://firebase.google.com/support/release-notes/android

**Comment by bsscco** [comment]
build.gradle에서 
com.google.firebase:firebase-analytics가 이미 추가돼있고
com.google.firebase:firebase-core 요것만 지우면 되는 것 같은데 맞을까요?!

**Comment by Pluu** [comment]
@bsscco dependency를 확인해보시고 제거처리 해주시면 됩니다
