### ISSUE TITLE
Migration, Data Class

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2020_App#53]
## Kind (Required)
- Improvement

 ## Overview (Required)

- Layered Architecture에서 모델을 공유하는 것은 간단한 방법일 수 있습니다. 
- SessionData/SpeakerData 는 ui package에 있지만, 실제로 그것은 ui를 위한 데이터가 아닙니다.
- 순수한 도메인으로서 접근한 모델 대응이 필요합니다.

```
ui
├── SessionData.kt
└── SpeakerData.kt
```

### 수정할 내용
- Data / UI Model 분리

**Comment by yands11** [comment]
🙋‍♂️

**Comment by Pluu** [comment]
@yands11 Thank you
