### ISSUE TITLE
Update, Kotlin Coroutine

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2020_App#54]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Android 개발시 VIewModel에서 Coroutine을 사용하고 싶은 경우, `CoroutineScope`를 구현했습니다. 이것은 문제가 되는 패턴은 아닙니다. 그러나, AAC에서 올바른 Job에 대한 처리가 필요합니다. 
- 현재 아래 코드는 uiScope로 하나의 코루틴이 에러가 난 경우 다른 코루틴도 모두 취소가 되는 문제가 발생합니다.
- 다양한 대안이 있지만, Google에서 제공하는  기본 패턴을 사용해볼 수 있습니다.

```kotlin
private val job = Job()
val uiScope = CoroutineScope(Dispatchers.Main + job)
```

 ## Links	

- https://medium.com/androiddevelopers/easy-coroutines-in-android-viewmodelscope-25bffb605471

**Comment by improve777** [comment]
🙋‍♀️🙋🙋‍♂️

**Comment by Pluu** [comment]
@improve777 Thank you
