### ISSUE TITLE
Kotlin AndroidExtension 다이어트

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2020_App#58]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Kotlin AndroidExtension에는 [Importing synthetic properties](https://kotlinlang.org/docs/tutorials/android-plugin.html#importing-synthetic-properties) 처리가 존재합니다.
- 위 기능으로 UI 접근을 손쉽게 가능하지만, 부가적인 이슈가 존재합니다. 그로 인해 Google측에서 권장하는 방법은 아닙니다. 또한 우리는 DataBinding이라는 좋은 수단을 사용하고 있습니다.
- synthetic 를 제거하는 처리를 도입하고 싶습니다.

 ## Links	

- https://medium.com/@BladeCoder/a-study-of-the-parcelize-feature-from-kotlin-android-extensions-59a5adcd5909

**Comment by bsscco** [comment]
🙋‍♀️🙋🙋‍♂️

**Comment by Pluu** [comment]
@bsscco Thank you
