### ISSUE TITLE
다크모드 전환 스위치 생성하기

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#62]
## Kind (Required)

- Improvement

 ## Overview (Required)

- mypage 페이지에 다크모드 적용 on/off 토글을 생성합니다.

 ## Links	

-

**Comment by laco-dev** [comment]
질문이 두 가지 있는데요~
1. 토글 버튼은 다크모드 테스트를 위한 용도일까요 아니면 기획된 디자인이 있는가요?
2. 다크모드 전환에 따른 리소스 가이드가 정의된게 있나요? 컬러 리소스가 hex 하드코딩되어있는 것 같아서 컬러 리소스나 테마로 관리가 필요해 보입니다.

**Comment by Pluu** [comment]
@laco-dev @Jiyoung9310 아직 다크모드 관련 디자인이 없습니다.
그러므로 위 이슈는 유효하지않아 보이네요.

**Comment by Jiyoung9310** [comment]
앱 기획 변경의 이유로 이슈 잠시 닫겠습니다. (필요 시, 다시 재오픈합니다.)
