### ISSUE TITLE
세션 리스트 시간순 정렬하기

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#63]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 세션 리스트를 세션 시작 시간 기준으로 빠른 순 정렬합니다.
-  세션 시작 시간 데이터는 Session 데이터 클래스의 'time' 필드를 참고합니다.
- 만약 세션 시작 시간이 같다면, 'track' 기준으로 정렬합니다.

 ## Links	

-

**Comment by laco-dev** [comment]
🙋‍♀️🙋🙋‍♂️

**Comment by Pluu** [comment]
@laco-dev Thank you.
