### ISSUE TITLE
세션 리스트 필터 추가

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#64]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 세션 리스트를 필터링 하는 기능을 추가한다.
- 세션 리스트 하단의 floating button 을 클릭 시, 필터 페이지를 띄운다.
- 필터 항목은 Session 데이터클래스에 있는 'tag' 필드를 전부 받아와서 표시해준다.

 ## Links	

-

**Comment by AshtonYoon** [comment]
🙋

**Comment by AshtonYoon** [comment]
``Beginner``
``Rx``
``UI``
``Kotlin``
``Architecture``

모든 태그 종류는 이렇게 5개가 맞을까요? @Jiyoung9310

**Comment by AshtonYoon** [comment]
![image](https://user-images.githubusercontent.com/16028154/87225169-12870180-c3c6-11ea-8014-148cb9d2c1f0.png)

ScheduleFilterFragment를 새로 만들어서 작업 중입니다

**Comment by Jiyoung9310** [comment]
@AshtonYoon 현재 태그 종류는 언급하신 다섯가지가 맞습니다! 앞으로 더 추가될 예정이니 고려해서 작업해주시면 감사하겠습니다! 👍

**Comment by AshtonYoon** [comment]
![image](https://user-images.githubusercontent.com/16028154/87577347-bac20080-c70d-11ea-8655-e415efdbf20e.png)
![image](https://user-images.githubusercontent.com/16028154/87577362-c281a500-c70d-11ea-8d31-cd5955a8c40f.png)

필터기능 구현 끝냈습니다~! 마무리 작업하고 코드 올려두도록 하겠습니다!
