### ISSUE TITLE
각 페이지 프래그먼트 화면에 꽉차게 표현

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2020_App#68]
## Kind (Required)
- Proposal
- Improvement

 ## Overview (Required)
- 기존 Bottom Navigation과 각 페이지 프래그먼트 사이에 몇 가지 이슈가 있습니다.
1. 프래그먼트와 Bottom Navigation이 Constraint로 붙어있어 배경색 지정의 어려움
(Bottom Navigation 밖의 주변 배경과 프래그먼트 배경이 따로 노는 현상)
2. RecyclerView 같은 스크롤의 영역이 화면의 가장 밑이 아닌 경계선까지 잡히는 문제

## Suggestion
- 아래 스크린샷과 같이 변경 해 보았는데, 괜찮다면 PR 올려보고자 합니다.

## Screenshot
Before | After
:--: | :--:
<img src="https://user-images.githubusercontent.com/28249981/75784115-0ef2c680-5da5-11ea-8bb7-480eeb904830.jpg" width="300" /> | <img src="https://user-images.githubusercontent.com/28249981/75784118-1023f380-5da5-11ea-9126-9d2db9c49fd6.jpg" width="300" />

**Comment by Jiyoung9310** [comment]
@laco-dev PR 날려주세요! 🙌
