### ISSUE TITLE
Navigation SafeArgs 적용

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2020_App#74]
## Kind (Required)
- Proposal
- Improvement

 ## Overview (Required)
-  네비게이션 라이브러리를 사용함에 따라 SafeArgs를 적용하면 보다 좋은 퀄리티의 개발 참고자료가 될 수 있을 것 같습니다.
- 현재 적용 대상: Session -> Session Detail
- 추가로 기존 네비게이션 이동 방식을 `destination` -> `action`을 사용하도록 변경하면 좋을 듯 합니다.
(#13 의 논의 결과에 따라 결정이 달라질 수 있겠네요. 💦 )

**Comment by Pluu** [comment]
`SafeArgs` 👍
