### ISSUE TITLE
RecyclerView No Adapter attached; skipping layout

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2020_App#75]
**Overview (Required)**
- 페이지 전환 이후 뒤로가기를 통해 이전 페이지로 돌아온 경우 리사이클러뷰의 어댑터 에러가 발생하면서 리스트가 그려지지 않는다.

**Steps To Reproduce**
- 이벤트 정보 -> 세션 or 프로필 -> 뒤로가기
- 세션 -> 세션 상세보기 -> 뒤로가기(이 항목은 현재 master 기준에서는 확인이 어려울 수 있습니다)
- 에러 발생 및 화면에 리스트가 그려지지 않음
```
E/RecyclerView: No adapter attached; skipping layout
```

**Expected behavior**
- 정상적으로 화면에 리스트가 나타나야 함.

**Screenshots**
<div align="center">
<img src="https://user-images.githubusercontent.com/28249981/76084239-c6c8e380-5ff2-11ea-9841-7f91edf0fe7d.jpg" height=320/>
<img src="https://user-images.githubusercontent.com/28249981/76084243-c7fa1080-5ff2-11ea-952d-d0cbe559a22e.jpg" height=320/>
</div>

**Additional context**
- observe를 통해 리스트를 받아오는 상황에서까지는 어댑터가 살아있는데, 이후 실제로는 그려지지 않고 있습니다.
- DI나 베이스 쪽이 의심스러운데 계속 찾아봤지만 아직 원인을 찾지 못하였습니다 😭

**Comment by Pluu** [comment]
🙏Thanks. 확인해보겠습니다

**Comment by Pluu** [comment]
I found the problem. And will report.
