### ISSUE TITLE
toolbar UI 표시하기

### ISSUE THREAD

**Issue by Jiyoung9310** [droidknights/DroidKnights2020_App#84]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 상단 툴바에 각 페이지마다 알맞는 페이지명을 표시한다.
- 스폰서 페이지 : "스폰서"
- 일정 페이지 : "일정"
- 설정 페이지 : "설정"
- background Color : white FFFFFF
- toolbar title text size : "20sp"
- toolbar title text color : black 000000

 ## Links	

- 앱 기획서 : https://docs.google.com/presentation/d/1ka9trEJrx-cDt98uG1j6DJRcNFtRZHggk_8OAqZdog8/edit?usp=sharing

**Comment by lagoJin** [comment]
🙋‍♂️

**Comment by Pluu** [comment]
@lagoJin Thank you

**Comment by lagoJin** [comment]
@Pluu 
툴바 텍스트의 경우 한글 영어 모두 지원해야 하나요? 
둘 중 한가지의 케이스만 대응하면 될까요?

**Comment by Pluu** [comment]
@lagoJin 현재는 한글 단일 언어도 무방합니다. string resource를 이용해주시면 감사합니다 :)
